date.timezone=Asia/Seoul
display_errors=Off
log_errors=Off
expose_php=Off
upload_max_filesize=20M
post_max_size=128M
max_file_uploads=10
memory_limit=256M
session.cookie_httponly=1
session.cookie_samesite=Strict
